backend:
  name: git-gateway
  branch: master
  repo: bfuller7141/Los-Alamos-Landscaping
  accept_roles:
    - admin
    - editor
  api_root: https://gitlab.com/api/v4
logo_url: /images/logos/lalam-logo_wordmark.svg

media_folder: "public/images/uploads"
public_folder: "public/images/uploads"

collections:
  - name: "services"
    label: "Services"
    folder: "src/content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Page Title", name: "pageTitle", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Icon", name: "icon", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Button Text", name: "btntxt", widget: "string"}
      - {label: "About", name: "about", widget: "textarea"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Alt Text", name: "alt", widget: "string"}
      - {label: "About Image", name: "imageTwo", widget: "image"}
      - {label: "Alt Text", name: "altTwo", widget: "string"}
      - {label: "Gallery", name: "gallery", widget: "list", fields: [{label: "Image", name: "image", widget: "image"}, {label: "Image Description", name: "alt", widget: "text"}]}

  - name: "testimonials"
    label: "Testimonials"
    folder: "src/content/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Rating", name: "rating", widget: "number", min: 1, max: 5, required: true}
      - {label: "Name", name: "name", widget: "string", required: true}
      - {label: "Testimonial", name: "testimonial", widget: "text", required: true}

  - name: "team"
    label: "Team"
    folder: "src/content/team"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string", required: true}
      - {label: "Role", name: "role", widget: "string", required: true}
      - {label: "Image", name: "image", widget: "image", required: true}

  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Project Description", name: "description", widget: "text", required: true}
      - {label: "Main Image", name: "image", widget: "image", required: true}
      - {label: "Alt Text", name: "mainAlt", widget: "string", required: true}
      - {label: "Image Two", name: "imageTwo", widget: "image", required: true}
      - {label: "Alt Text", name: "altTwo", widget: "string", required: true}
      - {label: "About Project", name: "about", widget: "textarea"}
      - {label: "Article Link", name: "articleLink", widget: "string"}
      - {label: "Gallery", name: "gallery", widget: "list", fields: [{label: "Image", name: "image", widget: "image"}, {label: "Image Description", name: "alt", widget: "text"}]}

  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    extension: "md"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "TitlePage", name: "titlePage", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "datetime", required: true}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: true}
      - {label: "Cover Image", name: "coverImage", widget: "image", required: true}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Slug", name: "slug", widget: "string", required: true}
      - {label: "Article", name: "article", widget: "markdown", required: true}
      - {label: "Excerpt", name: "excerpt", widget: "string", required: true}
